### ISSUE TITLE
Unable to migrate wiki from Redmine to GitLab

### ISSUE THREAD

**Issue by fsolans** [redmine-gitlab-migrator/redmine-gitlab-migrator#29]
Hi, I'm trying to import wiki and I have this error:

fsolans@fsolans-ThinkPad-L430:~$ **sudo migrate-rg pages --redmine-key XXX --gitlab-wiki czdecoder.wiki.git http://xxxprojects/xxdecoder** 
Collecting Conceptos_código_fuente
Traceback (most recent call last):
  File "/usr/local/bin/migrate-rg", line 11, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.3', 'console_scripts', 'migrate-rg')()
  File "/usr/local/lib/python3.6/dist-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 396, in main
  File "/usr/local/lib/python3.6/dist-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 185, in perform_migrate_pages
TypeError: must be str, not int

Any idea ? Thks !

**Comment by fsolans** [comment]
I have repaired it changing this in source code : 

fsolans@fsolans-ThinkPad-L430:~/storage/Dropbox/neodoo/accesos/aws/redmine-gitlab-migrator$ git diff
diff --git a/redmine_gitlab_migrator/commands.py b/redmine_gitlab_migrator/commands.py
index 27c1f83..b7cd0e0 100644
--- a/redmine_gitlab_migrator/commands.py
+++ b/redmine_gitlab_migrator/commands.py
@@ -182,7 +182,7 @@ def perform_migrate_pages(args):
     for page in redmine_project.get_all_pages():
         print("Collecting " + page["title"])
         start_version = page["version"] if args.no_history else 1
-        for version in range(start_version, page["version"]+1):
**+        for version in range(int(start_version), int(page["version"])+1):**
             try:
                 full_page = redmine_project.get_page(page["title"], version)
                 pages.append(full_page)
