### ISSUE TITLE
Problem with project containing versions

### ISSUE THREAD

**Issue by SolidTux** [redmine-gitlab-migrator/redmine-gitlab-migrator#30]
I get this error

```
INFO: Getting redmine issues
INFO: Converting issues
INFO: Creating gitlab issues
WARNING: Redmine issue #70 is anonymous, gitlab issue is attributed to current admin

Traceback (most recent call last):
  File "/opt/conda/bin/migrate-rg", line 11, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.3', 'console_scripts', 'migrate-rg')()
  File "/opt/conda/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 396, in main
  File "/opt/conda/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 246, in perform_migrate_issues
  File "/opt/conda/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 241, in <genexpr>
  File "/opt/conda/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/converters.py", line 242, in convert_issue
KeyError: '1.0.0'
```

1.0.0 is the target version of issue #70 and the issue state is rejected.

**Comment by SolidTux** [comment]
I just saw that this is the same as #14 .
