### ISSUE TITLE
Error migrating wiki

### ISSUE THREAD

**Issue by cesguerra** [redmine-gitlab-migrator/redmine-gitlab-migrator#40]
Hi, I am trying to migrate our wiki from Redmine 2.6.6 to GitLab 11.3.4 but the following error occurs: 

> Converting home (Wiki version 1)
Traceback (most recent call last):
  File "/usr/local/bin/migrate-rg", line 11, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.3', 'console_scripts', 'migrate-rg')()
  File "/usr/local/lib/python3.6/dist-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 396, in main
  File "/usr/local/lib/python3.6/dist-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 196, in perform_migrate_pages
  File "/usr/local/lib/python3.6/dist-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/wiki.py", line 148, in convert
  File "/usr/local/lib/python3.6/dist-packages/GitPython-2.1.11-py3.6.egg/git/index/base.py", line 741, in add
    entries_added.extend(self._entries_for_paths(paths, path_rewriter, fprogress, entries))
  File "/usr/local/lib/python3.6/dist-packages/GitPython-2.1.11-py3.6.egg/git/util.py", line 70, in wrapper
    raise InvalidGitRepositoryError("Method '%s' cannot operate on bare repositories" % func.__name__)
git.exc.InvalidGitRepositoryError: Method '_entries_for_paths' cannot operate on bare repositories

Command that I am using:

> migrate-rg pages --redmine-key REDMINE_KEY --gitlab-wiki /var/opt/gitlab/git-data/repositories/root/wiki-test.wiki.git/ REDMINE_PROJECT_URL

Python version:

> python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19)

**Comment by hkato** [comment]
Your steps are wrong.

This repository is git bare. 

> /var/opt/gitlab/git-data/repositories/root/wiki-test.wiki.git/ 

> git.exc.InvalidGitRepositoryError: Method '_entries_for_paths' cannot operate on bare repositories

please use none-bare git repository.

1. clone wiki repos.

```sh
$ mkdir -p ~/some/where
$ cd ~/some/where
$ git clone git@gitlab.yourdomain.example.com:root/wiki-test.wiki.git
```

2. migrate

```sh
$ migrate-rg pages --redmine-key REDMINE_KEY --gitlab-wiki ~/some/where/wiki-test.wiki.git/ REDMINE_PROJECT_URL
```

3. push remote

```sh
$ git push -u origin
```

Cc: @scambra I think you can close this issue.
