### ISSUE TITLE
neither pip install nor setup.py install work

### ISSUE THREAD

**Issue by martinbe1io** [redmine-gitlab-migrator/redmine-gitlab-migrator#56]
Hi, 

thanks for the migrator package, unfortunately it does not work for me as it complained about a logging issue. 
Second try cloning the repository, python setup.py install, give it a try by only running migrate-rg:

```
root@mfdev2:/home/mf/gitlab# migrate-rg 
Traceback (most recent call last):
  File "/usr/local/bin/migrate-rg", line 11, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.3', 'console_scripts', 'migrate-rg')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/redmine_gitlab_migrator/commands.py", line 8, in <module>
    (exitstatus, outtext) = commands.getstatusoutput(cmd)
  File "build/bdist.linux-x86_64/egg/redmine_gitlab_migrator/gitlab.py", line 6, in <module>
ImportError: No module named request
root@mfdev2:/home/mf/gitlab# 
```

any idea what's wrong?

Martin

**Comment by martinbe1io** [comment]
I managed to run it after enabling python3.5 and installed pip3

```
Install python3.5
Install pyhton3-pip3
 
root@mfdev2:/home/mf/gitlab# pip3 install git+https://github.com/redmine-gitlab-migrator/redmine-gitlab-migrator
```
 
now it runs, but looks like and endless loop downloading tons of usernames - is this a normal beavioure as I migrate to gitlab.com? 

```
migrate-rg issues --debug --user-dict /home/mf/gitlab/users.dict --no-sudo --redmine-key $redmine_key --gitlab-key $gitlab_key \
  $redmineproject $gitlabproject
```

**Comment by scambra** [comment]
You must use --project-members-only flag, as explained in readme:

Migrate issues get all users in gitlab. If you have many users in your gitlab, e.g. migrating to gitlab.com, it will be a slow process. You can use --project-members-only to query project members instead of all users, if corresponding user can't be found in project members, the issue/comment will be assigned to the gitlab admin user.

**Comment by martinbe1io** [comment]
thx, 

finally this did the job, the debug flag was really useful a missing pandoc installation was the last error and the project-members-only to prevent this long lasting download in the beginning
 
```
logfile=migrate.log
rm $logfile
 
migrate-rg roadmap --debug  --no-sudo --redmine-key $redmine_key --gitlab-key $gitlab_key \
  $redmineproject $gitlabproject  >> $logfile 2>> $logfile
 
migrate-rg issues --project-members-only --keep-id --debug --user-dict /home/mf/gitlab/users.dict --no-sudo --redmine-key $redmine_key --gitlab-key $gitlab_key \
  $redmineproject $gitlabproject  >> $logfile 2>> $logfile
~                                                            
```
